@startuml
skinparam actorStyle awesome

:Admin: as Admin

(Просмотреть список активных заказов) as ShowActiveOrders
(Просмотреть историю всех заказов) as ShowFullOrdersHistory
(Вывести подробную информацию о заказе) as AdditionalData

(Найти заказ с помощью поиска) as FindOrder
(Управлять состоянием заказа) as ManageOrderState
(Поменять состав заказа) as ChangeOrderComposition
(Скачать полезную нагрузку заказа) as DownloadOrderPayload
(Изменить статус заказа) as ChangeOrderStatus

(Поменять описание товара) as RenameItem
(Скрыть товар) as HideItem
(Поменять превью товара) as ChangeItemPreview
(Загрузить полезную нагрузку товара) as UploadOrderPayload
(Добавить товар в каталог) as AddItemIntoCatalogue
(Управлять каталогом товаров) as ManageCatalog

Admin --- ShowActiveOrders
Admin --- ManageCatalog
Admin --- ShowFullOrdersHistory
Admin --- ManageOrderState
Admin --- AddItemIntoCatalogue

RenameItem ...> ManageCatalog : extend
HideItem ...> ManageCatalog : extend
ChangeItemPreview ...> ManageCatalog : extend
UploadOrderPayload ..> ManageCatalog : extend
AdditionalData ..> ShowActiveOrders : extend
AdditionalData ..> ShowFullOrdersHistory : extend
FindOrder ..> ShowFullOrdersHistory : extend

ChangeOrderComposition ..> ManageOrderState : extend
ChangeOrderStatus ..> ManageOrderState : extend
DownloadOrderPayload ..> ManageOrderState : extend

@enduml