@startuml

skinparam actorStyle awesome

:User: as User
:Logged User: as Logged

(Просмотреть список товаров) as View
(Зайти в аккаунт) as Login
(Выйти из аккаунта) as Logout
(Просмотреть карточку товара) as Item
(Сортировать список товаров) as Sort
(Добавить товар в корзину) as Cart
( ) as DeleteFromCart
(Изменить количество товара в корзине) as ChangeAmountInCart
(Оформить заказ) as Checkout
(Изменить персональные данные) as ChangePersonalData
(Просмотреть историю заказов\nаккаунта и их состав) as OrderHistory
(Скачать полезную нагрузку заказа) as DownloadOrderPayload

Logged ---|> User

Logged --- Checkout
Logged --- Logout
Logged --- ChangePersonalData
Logged --- OrderHistory
User --- View
User --- Login
User --- Cart
User --- Register
User --- RecoverPassword

Item ...> View : include
Sort ...> View : include
Checkout ..> Cart : include
DeleteFromCart ...> Cart : extend
ChangeAmountInCart ...> Cart : extend
DownloadOrderPayload ..> OrderHistory : extend

note right of Logged : Не может заходить в аккаунт и\nи зарегистрироваться

@enduml