@startuml
skinparam actorStyle awesome
:User: as User
:Logged User: as Logged
:Admin: as Admin

(Просмотреть список товаров) as View
(Зайти в аккаунт) as Login
(Выйти из аккаунта) as Logout
(Просмотреть карточку товара) as Item
(Сортировать список товаров) as Sort
(Добавить товар в корзину) as Cart
(Удалить товар из корзины) as DeleteFromCart
(Изменить количество товара в корзине) as ChangeAmountInCart
(Оформить заказ) as Checkout
(Изменить персональные данные) as ChangePersonalData
(Просмотреть историю заказов\nи их состав) as OrderHistory
(Просмотреть список последних заказов) as ShowActiveOrders
(Управлять каталогом товаров) as ManageCatalog
(Переименовать товар) as RenameItem
(Скрыть товар) as HideItem
(Поменять превью товара) as ChangeItemPreview
(Удалить товар из каталога) as DeleteItemFromCatalog
(Изменить статус заказа) as ChangeOrderStatus

Logged ---|> User

Logged --- Checkout
User --- View
User --- Login
User --- Cart
ChangePersonalData --- Logged
OrderHistory --- Logged
Admin --- Login
Admin --- ShowActiveOrders
Admin --- ManageCatalog
Logged --- Logout

Item ...> View : include
Sort ...> View : include
DeleteFromCart ...> Cart : extend
ChangeAmountInCart ...> Cart : extend
Cart ..> Checkout : include
RenameItem ...> ManageCatalog : extend
HideItem ...> ManageCatalog : extend
ChangeItemPreview ...> ManageCatalog : extend
DeleteItemFromCatalog ...> ManageCatalog : extend

ChangeOrderStatus ..> ShowActiveOrders : extend
@enduml